In [5]:
print('sd')

sd


In [6]:
import numpy as np

print(np.__version__)

2.5.2


In [ ]:
#uv add torch torchvision

import torch

#버전 확인
print(torch.__version__)

#cuda 지원확인
print(torch.cuda.is_available())

2.13.0+cpu
False


PyTorch에서 GPU 가속 사용 가능 여부를 확인하고 장치(Device)를 지정

In [12]:
import torch
import torch.nn as nn

# 1. 실행 환경에 맞는 장치(Device) 동적 할당 (표준 패턴)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("현재 사용 장치:", device)

# 2. 텐서 생성 시 처음부터 지정된 장치로 할당 (메모리 이동 오버헤드 방지)
x = torch.ones((2, 3), device=device)

# 3. 기존 텐서를 지정 장치로 이동
# Note: 텐서의 .to()는 원본을 변경하지 않고 '새로운 텐서'를 반환합니다.
y = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
y = y.to(device)

# 4. 신경망 모델을 지정 장치로 이동
# Note: 모델의 .to()는 모델 내부 파라미터를 'In-place(제자리)'로 이동시킵니다.
model = nn.Linear(2, 2).to(device)

# 5. 모델 연산 실행
output = model(y)
print("출력 결과 장치:", output.device)

현재 사용 장치: cpu
출력 결과 장치: cpu


## 1.1 데이터로부터 직접 생성 (From Data)

In [20]:
a = torch.tensor(([1,2],[3,4]))

print(a)
print(a.dtype)

tensor([[1, 2],
        [3, 4]])
torch.int64


In [23]:


# 1-1. Python 리스트로부터 생성
list_data = [[1, 2, 3], [4, 5, 6]]
print(f'list_data: {list_data}')
print(type(list_data))


tensor_from_list = torch.tensor(list_data, dtype=torch.float32)
print(f'List -> Tensor: {tensor_from_list}')
print(type(tensor_from_list))   #<class 'torch.Tensor'>
print(tensor_from_list.dtype)
print(tensor_from_list.device)

list_data: [[1, 2, 3], [4, 5, 6]]
<class 'list'>
List -> Tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])
<class 'torch.Tensor'>
torch.float32
cpu


In [ ]:
#numpy 배열로 부터 생성
np_array = np.array([10,20,30])

#from_numpy()로 tensor()를 생성하면 메모리를 공유한다.
tensor_from_np = torch.from_numpy(np_array)
print(f'tenspr_from_np: {tensor_from_np}')

tensor_from_np[0] = 999
print(f'np_array: {np_array}')
print(f'tensor_from_np: {tensor_from_np}')

np_array[0] = 500
print(f'np_array: {np_array}')
print(f'tensor_from_np: {tensor_from_np}')


tenspr_from_np: tensor([10, 20, 30])
np_array: [999  20  30]
tensor_from_np: tensor([999,  20,  30])
np_array: [500  20  30]
tensor_from_np: tensor([500,  20,  30])


## 1.2 특정 형태(Shape)와 값으로 초기화 (Structured Initialization)

In [ ]:
shape = (2, 3)
print(f'zeros: {torch.zeros(shape)}')
print(f'ones: {torch.ones(shape)}')
print(f'empty: {torch.empty(shape)}')
print(f'full: {torch.full(shape, 3)}')

#범위기반 생성
print(f'arange: {torch.arange(10)}')        #end
print(f'arange: {torch.arange(0, 10)}')     #start, end
print(f'arange: {torch.arange(0, 10, 2)}')  #start, end, step

print(f'linspace: {torch.linspace(1,10, 5)}')  #start, end, step(1부터 10까지 5등분)


zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones: tensor([[1., 1., 1.],
        [1., 1., 1.]])
empty: tensor([[1., 1., 1.],
        [1., 1., 1.]])
full: tensor([[3, 3, 3],
        [3, 3, 3]])
arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


## 1.3. 무작위 난수로 초기화 (Random Initialization)

In [55]:
#난수 생성 시 재현성을 위한 시드(seed) 고정

torch.manual_seed(42)

print(f'rand: {torch.rand(2,2)}')


print(f'rand: {torch.rand(2,2,3)}')
print(f'rand: {torch.rand(2, 2, 3)}')


print(f'randn: {torch.randn(2,2)}')
print(f'randint: {torch.randint(1,10, (2,2))}')
print(f'randint: {torch.randint(low=1, high=10, size= (2,2))}')

print(f'randperm: {torch.randperm(10)}')


rand: tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
rand: tensor([[[0.3904, 0.6009, 0.2566],
         [0.7936, 0.9408, 0.1332]],

        [[0.9346, 0.5936, 0.8694],
         [0.5677, 0.7411, 0.4294]]])
rand: tensor([[[0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414]],

        [[0.2969, 0.8317, 0.1053],
         [0.2695, 0.3588, 0.1994]]])
randn: tensor([[-0.9890,  0.9580],
        [ 1.3221,  0.8172]])
randint: tensor([[3, 6],
        [2, 4]])
randint: tensor([[3, 4],
        [2, 4]])
randperm: tensor([7, 9, 1, 5, 0, 4, 8, 3, 6, 2])


## 1.4. 기존 텐서의 속성을 복사하여 초기화 (_like 계열)

In [ ]:
# x = torch.tensor([[1, 2, 3],
#                      [4, 5, 6]])

x = torch.tensor([[1, 2, 3],[4, 5, 6]], dtype=torch.float32)
# print(f'x: {x}')

#shap와 dtype을 그대로 복사해 온다.
x_zeros = torch.zeros_like(x)
print(f'zeros_like: {x_zeros}, dtype:{x_zeros.dtype}')

x_ones = torch.ones_like(x)
print(f'ones_like: {x_ones}, dtype:{x_ones.dtype}')

x_rand = torch.rand_like(x)
print(f'rand_like: {x_rand}, dtype:{x_rand.dtype}')

#ranit_like()는 x의 타입이 float32이므로 그 타입을 그대로 따라서 사용이 된다.(주의!)
x_randit = torch.randint_like(x, 10)
print(f'randint_like: {x_randit}, dtype:{x_randit.dtype}')

zeros_like: tensor([[0., 0., 0.],
        [0., 0., 0.]]), dtype:torch.float32
ones_like: tensor([[1., 1., 1.],
        [1., 1., 1.]]), dtype:torch.float32
rand_like: tensor([[0.0337, 0.1716, 0.3336],
        [0.5782, 0.0600, 0.2846]]), dtype:torch.float32
randint_like: tensor([[8., 9., 6.],
        [7., 6., 0.]]), dtype:torch.float32


## 1.5. 텐서의 주요 속성 (Attributes)

In [74]:
# 속성을 명시하며 텐서 생성
tensor_attr = torch.ones((2, 3), dtype=torch.float16, device="cpu")
print("Shape (차원):", tensor_attr.shape)
print("Datatype (타입):", tensor_attr.dtype)
print("Device (장치):", tensor_attr.device)


# 타입 변경 및 디바이스 이동
tensor_float32 = tensor_attr.to(dtype=torch.float32)
print("변경된 Datatype:", tensor_float32.dtype)


# GPU가 사용 가능한 경우 CUDA 장치로 이동
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("이동된 Device:", device )

Shape (차원): torch.Size([2, 3])
Datatype (타입): torch.float16
Device (장치): cpu
변경된 Datatype: torch.float32
이동된 Device: cpu


---

## 프로세스 요약 표

| STEP 01. Data Prep | STEP 02. Model Design | STEP 03. Setup | STEP 04. Training | STEP 05. Evaluation |
| :---: | :---: | :---: | :---: | :---: |
| **데이터 수집 & 전처리** | **`nn.Module` 구조 정의** | **손실함수 & 옵티마이저** | **5단계 학습 루프** | **성능 검증 & 평가** |
| `StandardScaler`<br>`DataLoader` | `Linear(30→32→16→1)`<br>`ReLU` / `Sigmoid` | `BCELoss`<br>`Adam (lr=0.001)` | `Forward` ➔ `Loss`<br>➔ `Zero` ➔ `Back` ➔ `Step` | `model.eval()`<br>`torch.no_grad()` |

---

## 📝 단계별 세부 프로세스 내용

### STEP 01. 데이터 로드 및 전처리
* **데이터셋 로드 및 분할**: Scikit-Learn 유방암 데이터셋(30개 특성)을 Train(80%)과 Test(20%)로 분할
* **특성 스케일링**: `StandardScaler`를 적용하여 데이터의 평균을 0, 표준편차를 1로 표준화
* **텐서(Tensor) 변환**: NumPy 배열을 PyTorch `float32` 텐서로 변환 (타겟 데이터 차원: `(N, 1)`)
* **미니배치 구성**: `TensorDataset`과 `DataLoader`를 사용해 `batch_size=32` 단위로 묶고 셔플(Shuffle) 설정

### STEP 02. 신경망 모델 클래스 정의
* **`nn.Module` 상속**: 커스텀 클래스 `BinaryClassifier` 정의
* **`__init__()` (레이어 초기화)**:
  * **Layer 1**: `nn.Linear(30, 32)` + `nn.ReLU()`
  * **Layer 2**: `nn.Linear(32, 16)` + `nn.ReLU()`
  * **Output Layer**: `nn.Linear(16, 1)` + `nn.Sigmoid()`
* **`forward()` (순전파 흐름)**: 입력 데이터 `x`가 은닉층을 거쳐 0~1 사이의 확률값으로 출력되는 연산 정의

### STEP 03. 손실 함수 및 옵티마이저 설정
* **손실 함수 (Loss Function)**: `nn.BCELoss()` (Binary Cross Entropy) — 이진 분류 예측값과 정답 간의 오차 측정
* **옵티마이저 (Optimizer)**: `optim.Adam(model.parameters(), lr=0.001)` — 효율적인 경사하강법 기반 가중치 최적화

### STEP 04. 모델 학습 루프 실행 (Training)
* **모드 전환**: `model.train()` 호출로 학습 모드 설정
* **미니배치 단위 5단계 학습 순서**:
  1. **Forward Pass**: `outputs = model(batch_X)` (예측값 계산)
  2. **Loss Calculation**: `loss = criterion(outputs, batch_y)` (손실값 측정)
  3. **Zero Grad**: `optimizer.zero_grad()` (이전 기울기 리셋)
  4. **Backward Pass**: `loss.backward()` (역전파로 기울기 계산)
  5. **Optimizer Step**: `optimizer.step()` (가중치 갱신)

### STEP 05. 모델 평가 및 성능 측정 (Evaluation)
* **평가 모드 전환**: `model.eval()`을 호출하여 DropOut/BatchNorm 동작 고정
* **기울기 계산 비활성화**: `with torch.no_grad():` 블록을 사용하여 메모리 절약 및 연산 속도 향상
* **임계값 적용**: Output 확률값이 `0.5` 이상이면 Class 1, 미만이면 Class 0으로 이진 분류
* **최종 평가**: 테스트 데이터셋의 **Test Loss** 및 **Accuracy(정확도 %)** 산출

# 텐서 사이즈(Tensor Size)


2.1 크기 및 차원 확인 (Size Inspection)

In [78]:
np.shape(x)
np.ndim(x)

2

In [85]:
# 1. 텐서 생성 및 기본 크기 확인
x = torch.arange(24).reshape(2, 3, 4) # (2, 3, 4) 크기의 3차원 텐서
# print(f'x: {x}')


print(f'size: {x.shape}')            # torch.Size([2, 3, 4])
print(f'ndim: {x.ndim}')             #3
print(f'size: {x.size(0)}')          #size(dim) =>size(0) =>2
print(f'numel: {x.numel()}')         #24: 텐서 내부의 전체요소갯수




size: torch.Size([2, 3, 4])
ndim: 3
size: 2
numel: 24


2.2 크기 변경 및 형상 조작 (Shape Manipulation)


In [ ]:
import torch

# 1. 텐서 생성 및 기본 크기 확인
x = torch.arange(24).reshape(2, 3, 4) # (2, 3, 4) 크기의 3차원 텐서

print("Shape:", x.shape)            # torch.Size([2, 3, 4])
print("Rank (차원 수):", x.ndim)    # 3
print("Total Elements:", x.numel()) # 24
print("1번 차원 크기:", x.size(1))  # 3

# 2. view와 reshape
x_view = x.view(2, 12)             # (2, 12)로 변경
x_auto = x.reshape(-1, 6)          # (4, 6)으로 자동 계산
 
# 3. unsqueeze & squeeze
x_2d = torch.randn(3, 4)           # Shape: (3, 4)
x_unsqueezed = x_2d.unsqueeze(0)   # Shape: (1, 3, 4) - 배치 차원 추가 시 활용
x_squeezed = x_unsqueezed.squeeze()# Shape: (3, 4)

# 4. permute (차원 재배치)
img_tensor = torch.randn(32, 3, 224, 224) # (Batch, Channel, Height, Width)
img_permuted = img_tensor.permute(0, 2, 3, 1) # (Batch, Height, Width, Channel)
print("\nPermuted Shape:", img_permuted.shape) # torch.Size([32, 224, 224, 3])

# 5. expand vs repeat
a = torch.tensor([[1], [2]])       # Shape: (2, 1)
a_expanded = a.expand(2, 4)        # 메모리 복사 없이 (2, 4)로 확장
a_repeated = a.repeat(1, 4)        # 실제 데이터를 4번 복사하여 (2, 4) 생성

In [98]:
x = torch.arange(24).reshape(2, 3, 4) # (2, 3, 4) 크기의 3차원 텐서

x = torch.arange(24).reshape(2,3,4) # (2,3,4) 크기의 3차원 텐서


# view()
x_view = x.view(2,12) # 2차원 행렬로 바꿔준것이다. 
print(x_view)       #2차원 행렬
x_auto = x.reshape(-1, 6)# 열은 6개로 고정하고 알아서 행렬을 만들어 달라는 뜻이다.
print(f'x_auto: {x_auto}')

x_2d = torch.randn(3, 4)           # Shape: (3, 4)


x_unsqueeze = x_2d.unsqueeze(0)
print(f'x_unsqueeze: {x_unsqueeze.shape}')

x_squeeze = x_unsqueeze.squeeze()
print(f'squeeze: {x_squeeze.shape}')

# permute (차원 재배치)
img_tensor = torch.randn(32, 3, 224, 224) # (Batch, Channel, Height, Width)
img_permuted = img_tensor.permute(0, 2, 3, 1) # (Batch, Height, Width, Channel)
print("\nPermuted Shape:", img_permuted.shape) # torch.Size([32, 224, 224, 3])


# 5. expand vs repeat
a = torch.tensor([[1], [2]])       # Shape: (2, 1)
print(f'expand: {a.expand(2,4)}')
print(f'repeat: {a.repeat(1,4)}')

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
x_auto: tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
x_unsqueeze: torch.Size([1, 3, 4])
squeeze: torch.Size([3, 4])

Permuted Shape: torch.Size([32, 224, 224, 3])
expand: tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]])
repeat: tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]])


## . 인덱싱, 슬라이싱 및 결합 (Indexing, Slicing & Joining)

In [100]:

# 3x4 크기의 2차원 텐서 생성
x = torch.tensor([[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12]])

print("원본 텐서:\n", x)

# 1. 단일 요소 접근 (1행 2열 -> 값: 7)
print("\n1. 특정 위치 요소 (1, 2):", x[1, 2].item())

# 2. 특정 행/열 전체 추출
print("2-1. 첫 번째 행 전체 (0, :):", x[0, :])
print("2-2. 마지막 열 전체 (:, -1):", x[:, -1])


# 3. 범위 슬라이싱 (0~1행, 1~2열 추출)
# [start:end]에서 end는 포함되지 않음
print("3. 부분 텐서 추출:\n", x[0:2, 1:3])

# 4. 간격 지정 슬라이싱 (step=2)
print("4. 2칸 간격 추출:", x[:, ::2])

원본 텐서:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

1. 특정 위치 요소 (1, 2): 7
2-1. 첫 번째 행 전체 (0, :): tensor([1, 2, 3, 4])
2-2. 마지막 열 전체 (:, -1): tensor([ 4,  8, 12])
3. 부분 텐서 추출:
 tensor([[2, 3],
        [6, 7]])
4. 2칸 간격 추출: tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])


### 3.2 고급 인덱싱 (Advanced Indexing)

In [102]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

# 1. 불리언 마스킹 (50보다 큰 요소만 추출)
mask = x > 50
print("마스크 (Boolean Tensor):\n", mask)
print("50보다 큰 값만 추출:", x[mask])  # 1차원 텐서로 반환됨

# 2. 인덱스 리스트를 활용한 추출 (팬시 인덱싱)
# 0행과 2행 추출
rows = torch.tensor([0, 2])
print("\n0행과 2행 추출:\n", x[rows])

# 3. torch.index_select 사용 (dim=1: 열 기준 추출)
cols = torch.tensor([0, 2]) # 0열과 2열 선택
selected_cols = torch.index_select(x, dim=1, index=cols)
print("0열과 2열 추출 (index_select):\n", selected_cols)

마스크 (Boolean Tensor):
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
50보다 큰 값만 추출: tensor([60, 70, 80, 90])

0행과 2행 추출:
 tensor([[10, 20, 30],
        [70, 80, 90]])
0열과 2열 추출 (index_select):
 tensor([[10, 30],
        [40, 60],
        [70, 90]])


In [103]:
x = torch.randn(2,3)
torch.stack((x, x), dim =1)

tensor([[[ 0.6887, -1.0693,  0.3843],
         [ 0.6887, -1.0693,  0.3843]],

        [[-0.7569,  1.3275, -1.9903],
         [-0.7569,  1.3275, -1.9903]]])

In [105]:
x = torch.randn(2,3)
torch.stack((x, x), dim =0)

tensor([[[ 1.1972,  0.7684,  1.2632],
         [ 0.8490, -0.7467, -2.0133]],

        [[ 1.1972,  0.7684,  1.2632],
         [ 0.8490, -0.7467, -2.0133]]])

# 3.4 텐서 분할 (Splitting Tensors)

In [107]:
x = torch.arange(12).reshape(4, 3) # 4행 3열 텐서
print("분할할 원본 텐서 (4x3):\n", x)

# 1. torch.split: 행 방향(dim=0)으로 2행씩 분할
split_result = torch.split(x, split_size_or_sections=2, dim=0)
print("\nsplit (크기 2씩 분할 결과):")
for t in split_result:
    print(t)

# 2. torch.chunk: 행 방향(dim=0)으로 총 2개의 덩어리로 분할
chunk_result = torch.chunk(x, chunks=4, dim=0)
print("\nchunk (2개로 등분 결과):")
for t in chunk_result:
    print(t)

분할할 원본 텐서 (4x3):
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

split (크기 2씩 분할 결과):
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

chunk (2개로 등분 결과):
tensor([[0, 1, 2]])
tensor([[3, 4, 5]])
tensor([[6, 7, 8]])
tensor([[ 9, 10, 11]])


In [108]:
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor = torch.tensor([0.5, 1.5, 2.5], dtype=torch.float32)

# int32 + float32 -> float32로 자동 승격
result = int_tensor + float_tensor
print("연산 결과:", result)
print("자동 승격된 dtype:", result.dtype) # torch.float32

연산 결과: tensor([1.5000, 3.5000, 5.5000])
자동 승격된 dtype: torch.float32


In [109]:
x = torch.tensor([1.0, 2.0, 3.0])
print("초기 메모리 주소:", id(x))

# Out-of-place 연산 (새로운 텐서 생성 -> 주소 변경됨)
x_new = x + 5.0
print("Out-of-place 후 x 주소:", id(x))

# In-place 연산 (기존 텐서 메모리에 즉시 반영 -> 주소 동일)
x.add_(5.0)
print("In-place 연산 후 x 값:", x)
print("In-place 후 x 주소:", id(x)) # 초기 주소와 동일함

# 모든 요소를 0으로 초기화
x.zero_()
print("zero_() 적용 후:", x)

초기 메모리 주소: 1828200566128
Out-of-place 후 x 주소: 1828200566128
In-place 연산 후 x 값: tensor([6., 7., 8.])
In-place 후 x 주소: 1828200566128
zero_() 적용 후: tensor([0., 0., 0.])
